name = "isoopod/react_emitter"
version = "0.1.0"
description = "2D Particle Emitter for React-lua"
authors = ["isoopod"]
repository = "https://github.com/isoopod/React-Emitter"
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }
UI_Labs = { name = "pepeeltoro41/ui_labs", version = "^2.4.2" }
ReactRoblox = { wally = "jsdotlua/react-roblox", version = "^17.2.1" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dependencies]
React = { wally = "jsdotlua/react", version = "^17.2.1" }
